version: '3.8'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: data_test
      POSTGRES_USER: data_test
      POSTGRES_PASSWORD: blank_password
    ports:
      - "5432:5432"
    networks:
      - spring-boot-debug

  pg-admin:
    container_name: pg-admin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - spring-boot-debug
    volumes:
      - pgadmin:/var/lib/pgadmin

  spring-app:
    container_name: spring-boot-debug-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
    volumes:
      - .:/app
    ports:
      - "8082:8082"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/data_test
      - SPRING_DATASOURCE_USERNAME=data_test
      - SPRING_DATASOURCE_PASSWORD=blank_password
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - spring-boot-debug
volumes:
    pgadmin:
networks:
  spring-boot-debug:
    driver: bridge  